### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by matthewlee07** [paircolumbus/MoreDrillsWithRSpec#96]
Current Gemfile uses ruby '2.0.0' which causes issues when running bundle from terminal. I removed the line with ruby. I also changed the gem line to just rspec

**Comment by mikegee** [comment]
I don't think we need to be specific about Ruby's version. Let's remove that line.

That specific RSpec version constraint is kinda weird. I suppose we should make it `'<4'`, just in case version 4 has some breaking changes whenever it comes out.

Wanna make a PR with just those changes?

**Comment by JeffMorhous** [comment]
Was having this issue myself. Removed the line and opened a PR so others won't encounter the same problems. Cheers

**Comment by mikegee** [comment]
Fixed by #102
